version: '2'

services:
  ping_monitoring:
    container_name:  ping_monitoring
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - influxDB
  influxDB:
    container_name: influxDB
    image: influxdb:1.8
    restart: 'on-failure'
    volumes:
      - /:/var/lib/docker/volumes/influxdb/_data
    ports:
      - '8086:8086'
  nginx:
    image: 'nginx'
    container_name: temp_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/etc/nginx/html/index.html
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - '80:80'
    restart: 'on-failure'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s/grafana/
    user: "1000"
    depends_on:
      - influxDB
